name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod download

    - name: Wait for DynamoDB
      run: |
        echo "Waiting for DynamoDB to be ready..."
        for i in {1..30}; do
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ | grep -q "400\|404"; then
            echo "DynamoDB is ready!"
            break
          fi
          echo "Waiting for DynamoDB... (${i}/30)"
          sleep 2
        done

    - name: Create DynamoDB tables
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_DEFAULT_REGION: us-east-1
      run: |
        # Create test_users table
        aws dynamodb create-table \
          --table-name test_users \
          --attribute-definitions AttributeName=id,AttributeType=S \
          --key-schema AttributeName=id,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST \
          --endpoint-url http://localhost:8000 \
          --region us-east-1 || true

        # Create test_users_with_sort table
        aws dynamodb create-table \
          --table-name test_users_with_sort \
          --attribute-definitions \
            AttributeName=user_id,AttributeType=S \
            AttributeName=timestamp,AttributeType=S \
          --key-schema \
            AttributeName=user_id,KeyType=HASH \
            AttributeName=timestamp,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST \
          --endpoint-url http://localhost:8000 \
          --region us-east-1 || true

        # Wait for tables to be active
        aws dynamodb wait table-exists \
          --table-name test_users \
          --endpoint-url http://localhost:8000 \
          --region us-east-1

        aws dynamodb wait table-exists \
          --table-name test_users_with_sort \
          --endpoint-url http://localhost:8000 \
          --region us-east-1

    - name: Run acceptance tests
      env:
        AWS_ENDPOINT_URL: http://localhost:8000
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_DEFAULT_REGION: us-east-1
      run: go test -count=1 -v ./... -tags=acceptance
